name = "id1"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "id1.effata.online"
custom_domain = true

[[routes]]
pattern = "dl.cvs.freefiremobile.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "df.game.naver.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "quiz.int.vidio.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "blog.webex.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "zaintest.vuclip.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "api.midtrans.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "edu.ruangguru.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "beta.zoom.us.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "api.zoom.us.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "store.zoom.us.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "zoomgov.socifiles.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "access.zoominfo.com.id1.effata.online"
custom_domain = true

[[routes]]
pattern = "data.mt.id1.effata.online"
custom_domain = true

[vars]
PROXYIP = "35.219.15.90"
UUID = "1d30fa45-9d31-4e81-a646-f8c7dbda0c65"
