name = "sg1"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "dl.cvs.freefiremobile.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "df.game.naver.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "quiz.int.vidio.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "blog.webex.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "zaintest.vuclip.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "api.midtrans.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "edu.ruangguru.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "beta.zoom.us.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "api.zoom.us.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "store.zoom.us.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "zoomgov.socifiles.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "access.zoominfo.com.sg1.effata.online"
custom_domain = true

[[routes]]
pattern = "data.mt.sg1.effata.online"
custom_domain = true

[vars]
PROXYIP = "15.235.162.49"
UUID = "1d30fa45-9d31-4e81-a646-f8c7dbda0c65"
